env: prod

spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 30
      initial-size: 3

