server:
  port: 80

netty:
  port: 11811

spring:
    profiles:
      active: @app.env@

mybatis:
  mapper-locations: classpath*:com/dyz/intellig/service/intelligserver/dao/**/*Mapper.xml

logging:
  config: classpath:log4j2/log4j2-@app.env@.xml